# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [pipeline]
  pull_request:
    branches: [trunk]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install npm packages and build frontend
        working-directory: ./assets/js
        run: npm install
      - name: build frontend
        working-directory: ./assets/js
        run: npm run build --if-present

      - name: Set up JDK 14.0.1
        uses: actions/setup-java@v1
        with:
          java-version: 14.0.1

      - name: Build with Maven
        working-directory: ./
        run: mvn clean install -Dvisual.skip.test=true
